### ISSUE TITLE
运行结果图片

### ISSUE THREAD

**Issue by GexinLiu** [cuhk-haosun/workshop-docker#7]
可不可以放一下你们按照你们写的代码运行的结果图片，让我们确信你们的代码都是可以正常运行的。 @fpfcap  @MeowBing @Murui-da @223050025

**Comment by fpfcap** [comment]
🆗 ，结果图会补充在文件夹中

**Comment by 223050025** [comment]
<img width="833" alt="截屏2024-04-05 03 06 20" src="https://github.com/cuhk-haosun/workshop-docker/assets/157484964/963c7548-6def-4b2b-b5c1-217b13346b37">
<img width="1355" alt="截屏2024-04-05 03 09 09" src="https://github.com/cuhk-haosun/workshop-docker/assets/157484964/aa33b5f6-8600-447e-b6a7-f79b6d0e384a">

**Comment by Milokita** [comment]
finshed
